import type { Ordre } from './ordre';

/** Eksempelbestilling som brukes til forhåndsvisning av e-postmaler. */
export const EKSEMPEL_ORDRE: Ordre = {
  id: '00000000-0000-0000-0000-000000000000',
  ordrenr: 'NS-1001',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  status: 'utkast_sendt',
  kunde_navn: 'Kari Nordmann',
  kunde_epost: 'kari@klippogkroll.no',
  kunde_telefon: '912 34 567',
  kommentar: '',
  bedrift_navn: 'Klipp & Krøll',
  orgnr: '',
  bransje: 'Frisør og skjønnhet',
  beskrivelse: 'Frisørsalong på Sandsli.',
  mal: ['Ta imot timebestillinger'],
  malgruppe: '',
  eksisterende_side: '',
  inspirasjon: '',
  tema: { id: 'rosa', navn: 'Moltekrem', stil: 'Leken' },
  sider: ['Forside', 'Tjenester', 'Priser', 'Kontakt'],
  egne_sider: '',
  funksjoner: [],
  tillegg: { booking: 1 },
  onsker: '',
  admin_valgt: true,
  admin_onsker: '',
  domene_valg: 'nytt',
  domene: 'klippogkroll.com',
  domene_aar: 2,
  domene_pris_nok: 160,
  domene_fornyelse_nok: 160,
  filer: [],
  pris_linjer: [
    { navn: 'Nettside – grunnpakke', belop: 1999 },
    { navn: 'Timebestilling', belop: 799 },
    { navn: 'Adminside (/admin)', belop: 999 },
    { navn: 'Domene klippogkroll.com', belop: 320, detalj: '2 år' },
  ],
  gebyr: 99,
  rest: 4117,
  total: 4216,
  rabatt: 0,
  gebyr_betalt: true,
  gebyr_betalt_at: new Date().toISOString(),
  rest_betalt: false,
  rest_betalt_at: null,
  rest_lenke: 'https://buy.stripe.com/test_eksempel',
  rest_lenke_id: '',
  utkast_url: 'https://klipp-og-kroll.vercel.app',
  live_url: '',
  github_repo: '',
  endringsrunder_brukt: 0,
  ai_brief: '',
  claude_prompt: '',
  notater: '',
  hosting_fornyes: null,
  domene_fornyes: null,
  vilkar_godtatt_at: null,
  bekreftelse_sendt: true,
};
